/* tslint:disable */
/* eslint-disable */
/**
 * Fasterbase
 * Fasterbase API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AuthLoginDto
 */
export interface AuthLoginDto {
    /**
     * 
     * @type {string}
     * @memberof AuthLoginDto
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof AuthLoginDto
     */
    'password': string;
}

