/* tslint:disable */
/* eslint-disable */
/**
 * Fasterbase
 * Fasterbase API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { UserResponseDto } from './user-response-dto';

/**
 * 
 * @export
 * @interface FindAllResponseDto
 */
export interface FindAllResponseDto {
    /**
     * 
     * @type {number}
     * @memberof FindAllResponseDto
     */
    'total': number;
    /**
     * 
     * @type {Array<UserResponseDto>}
     * @memberof FindAllResponseDto
     */
    'data': Array<UserResponseDto>;
}

