/* tslint:disable */
/* eslint-disable */
/**
 * Fasterbase
 * Fasterbase API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { PaginationDto } from './pagination-dto';
// May contain unused imports in some cases
// @ts-ignore
import { SorterDto } from './sorter-dto';

/**
 * 
 * @export
 * @interface FindAllDto
 */
export interface FindAllDto {
    /**
     * 
     * @type {PaginationDto}
     * @memberof FindAllDto
     */
    'pagination': PaginationDto;
    /**
     * 
     * @type {Array<SorterDto>}
     * @memberof FindAllDto
     */
    'sorters': Array<SorterDto>;
}

