# Base image
FROM node:18-alpine AS base
RUN npm i -g pnpm

FROM base AS dependencies

WORKDIR /app
COPY package.json pnpm-lock.yaml ./
RUN pnpm install

FROM base AS build

WORKDIR /app
COPY . .
COPY --from=dependencies /app/node_modules ./node_modules

ENV NODE_ENV production
RUN pnpm build:prod
RUN pnpm prune --prod

FROM base AS deploy
WORKDIR /app
COPY --from=build /app/public/ ./public/
COPY --from=build /app/dist/ ./dist/
COPY --from=build /app/node_modules ./node_modules
EXPOSE 8080
CMD [ "node", "dist/main" ]
